import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// jsPDF standard fonts don't support ₹, so we use Rs. in PDFs
function fmt(n) {
  return 'Rs. ' + Number(n).toLocaleString('en-IN');
}

export function downloadOrderPDF(order) {
  const doc = new jsPDF();
  const pageW = doc.internal.pageSize.getWidth();

  // ── Header ──────────────────────────────────────────────
  doc.setFillColor(88, 28, 135); // purple
  doc.rect(0, 0, pageW, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('HardwareHub', 14, 16);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Inventory Management System', 14, 24);
  doc.text('TAX INVOICE', pageW - 14, 16, { align: 'right' });

  // ── Order Meta ───────────────────────────────────────────
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Order ID: ${order.id}`, 14, 52);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${new Date(order.createdAt).toLocaleString('en-IN')}`, 14, 60);
  doc.text(`Total Items: ${order.itemCount} types  |  Total Units: ${order.totalQty}`, 14, 68);

  // ── Items Table ──────────────────────────────────────────
  autoTable(doc, {
    startY: 76,
    head: [['#', 'Product Name', 'SKU', 'Qty', 'Unit Price', 'Total']],
    body: order.items.map((item, i) => [
      i + 1,
      item.name,
      item.sku || '-',
      `${item.qty} ${item.unit || 'pcs'}`,
      fmt(item.unitPrice),
      fmt(item.total),
    ]),
    headStyles: { fillColor: [88, 28, 135], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    alternateRowStyles: { fillColor: [245, 243, 255] },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      3: { halign: 'center' },
      4: { halign: 'right' },
      5: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
  });

  // ── Totals ───────────────────────────────────────────────
  const finalY = doc.lastAutoTable.finalY + 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, finalY, pageW - 14, finalY);

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(88, 28, 135);
  doc.text('GRAND TOTAL', 14, finalY + 12);
  doc.text(fmt(order.subtotal), pageW - 14, finalY + 12, { align: 'right' });

  // ── Footer ───────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150);
  doc.text('Generated by HardwareHub • Thank you for your business!', pageW / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

  doc.save(`${order.id}.pdf`);
}
